//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    [Serializable]
    public class PoseEstimationServiceResponse : Message
    {
        public const string k_RosMessageName = "niryo_moveit/PoseEstimationService";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg estimated_pose1;
        public Geometry.PoseMsg estimated_pose2;
        public Geometry.PoseMsg estimated_pose3;
        public float estimated_scaleY1;
        public float estimated_scaleY2;
        public float estimated_scaleY3;

        public PoseEstimationServiceResponse()
        {
            this.estimated_pose1 = new Geometry.PoseMsg();
            this.estimated_pose2 = new Geometry.PoseMsg();
            this.estimated_pose3 = new Geometry.PoseMsg();
            this.estimated_scaleY1 = 0.0f;
            this.estimated_scaleY2 = 0.0f;
            this.estimated_scaleY3 = 0.0f;
        }

        public PoseEstimationServiceResponse(Geometry.PoseMsg estimated_pose1, Geometry.PoseMsg estimated_pose2, Geometry.PoseMsg estimated_pose3, float estimated_scaleY1, float estimated_scaleY2, float estimated_scaleY3)
        {
            this.estimated_pose1 = estimated_pose1;
            this.estimated_pose2 = estimated_pose2;
            this.estimated_pose3 = estimated_pose3;
            this.estimated_scaleY1 = estimated_scaleY1;
            this.estimated_scaleY2 = estimated_scaleY2;
            this.estimated_scaleY3 = estimated_scaleY3;
        }

        public static PoseEstimationServiceResponse Deserialize(MessageDeserializer deserializer) => new PoseEstimationServiceResponse(deserializer);

        private PoseEstimationServiceResponse(MessageDeserializer deserializer)
        {
            this.estimated_pose1 = Geometry.PoseMsg.Deserialize(deserializer);
            this.estimated_pose2 = Geometry.PoseMsg.Deserialize(deserializer);
            this.estimated_pose3 = Geometry.PoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.estimated_scaleY1);
            deserializer.Read(out this.estimated_scaleY2);
            deserializer.Read(out this.estimated_scaleY3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.estimated_pose1);
            serializer.Write(this.estimated_pose2);
            serializer.Write(this.estimated_pose3);
            serializer.Write(this.estimated_scaleY1);
            serializer.Write(this.estimated_scaleY2);
            serializer.Write(this.estimated_scaleY3);
        }

        public override string ToString()
        {
            return "PoseEstimationServiceResponse: " +
            "\nestimated_pose1: " + estimated_pose1.ToString() +
            "\nestimated_pose2: " + estimated_pose2.ToString() +
            "\nestimated_pose3: " + estimated_pose3.ToString() +
            "\nestimated_scaleY1: " + estimated_scaleY1.ToString() +
            "\nestimated_scaleY2: " + estimated_scaleY2.ToString() +
            "\nestimated_scaleY3: " + estimated_scaleY3.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
